### PR TITLE
Set up prose.io for editing prototype

### PR DESCRIPTION
**Pull request by dhcole**
This moves files around and adds configuration for prose.io as an editor. It's a first round prototype for the configuration, and here's what it enables:
## Current features
- web-based content editor for users
  screen shot 2015-05-19 at 10 25 46 pm
- markdown-assisted editor 
  screen shot 2015-05-19 at 10 25 59 pm
- drag-and-drop image upload that automatically writes out the image tag
  screen shot 2015-05-19 at 10 26 27 pm
- full template preview with actual site styles (bug: this is currently not displaying the site header)
  screen shot 2015-05-19 at 10 26 37 pm
- Form-based metadata editor (free text for permalink, dropdown for layout, in-line editable title)
  screen shot 2015-05-19 at 10 26 50 pm
- One-click commit with log message and diff
  screen shot 2015-05-19 at 10 27 14 pm
- Automatic publishing to github pages (could eventually be 18f-pages or something custom)
  screen shot 2015-05-19 at 10 28 01 pm
## Next steps
- resolve preview bug that's not rendering header
- better support for previewing `pages` (right now, the editor can only preview `_posts` with full layout)
- step up embedded editor (e.g. https://example.com/edit) with "Edit this page" links shown to logged-in admins
- prototype branch-based workflow with approval

### CODE REVIEW

**Comment by dhcole** [comment]
@blacktm @vzvenyach ready for your review. Go to http://prose.io/#dhcole/military-onesource-federalist and switch the branch to `editor` to try it.

**Comment by dhcole** [comment]
Submitted an upstream PR that should fix the header issue: https://github.com/prose/prose/pull/838

**Comment by vdavez** [comment]
I think this is ready for merge. Thanks @dhcole!

**Comment by vdavez** [comment]
D'oh. @blacktm, I'm not actually a "collaborator" on this repo. Can you merge and add me? Thanks!

**Comment by blacktm** [comment]
@vzvenyach Ok, I added the consulting team GitHub group as a collaborator. Let me know if you have issues.

**Pull request merged**
